title: <h1><a href="https://scicapt.github.io/">Sean Saliga</a></h1>
description: Physics and Math Student Pursuing STEM and R&D Opportunities
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
