title: SciCapt's Webpage
description: A bit about myself and some of the hobby projects I've done
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
