title: Sean Saliga
description: Physics and Math Student Pursuing R&D Opportunities
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
