title: SciCapt's Webpage
description: A place for me to share a bit about me and to showcase some of the hobby projects I've had.
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
