title: Sean Saliga
description: Junior Electrical Engineer at Electronic Design Associates and Recent Physics and Math Student from UF
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
