title: <a href="https://scicapt.github.io/"><h1>Sean Saliga</h1></a>
description: Physics and Math Student Pursuing STEM and R&D Opportunities
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
